# Generated by Django 6.0.7 on 2026-07-15 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_squashed_0004_alter_customuser_email_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="supporter_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OpenCollectiveDonation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("transaction_id", models.CharField(max_length=64, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("amount", models.IntegerField(help_text="Donation amount in cents.")),
                ("donated_at", models.DateTimeField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opencollective_donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
