# Generated by Django 6.0.7 on 2026-07-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_customuser_supporter_until_opencollectivedonation"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="supporter_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("friend", "Friend"),
                    ("backer", "Backer"),
                    ("sponsor", "Sponsor"),
                    ("mega_sponsor", "Mega Sponsor"),
                ],
                max_length=20,
            ),
        ),
    ]
