# Generated by Django 6.0.7 on 2026-07-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_customuser_supporter_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="opencollectivedonation",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[("monthly", "Monthly"), ("yearly", "Yearly"), ("onetime", "One-time")],
                help_text="The underlying OpenCollective order's frequency.",
                max_length=10,
            ),
        ),
    ]
