# Generated by Django 6.0.7 on 2026-08-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_apitoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("signups_enabled", models.BooleanField(default=True)),
                (
                    "disabled_message",
                    models.CharField(
                        blank=True,
                        default="New account signups are temporarily disabled. Please check back later.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Signup settings",
                "verbose_name_plural": "Signup settings",
            },
        ),
    ]
