repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.2
    hooks:
      - id: ruff
      - id: ruff-format
#   - repo: https://github.com/Riverside-Healthcare/djLint
#     rev: v1.36.4
#     hooks:
#       - id: djlint-reformat-django
# #      - id: djlint-django
