[tool.black]
line-length = 95
target-version = [ "py310",]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 95
default_section = "THIRDPARTY"
known_first_party = []
known_third_party = ["chartkick", "dal", "decouple", "django", "django_filters", "django_select2", "drf_spectacular", "pytest", "pytest_django", "rest_framework", "sorl", "storages"]

[tool.coverage.run]
source = ["comicsdb", "users", "metron"]

[tool.coverage.report]
show_missing = true