[tool.black]
line-length = 95
target-version = ["py310"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 95
default_section = "THIRDPARTY"
known_first_party = []
known_third_party = ["PIL", "chartkick", "dal", "decouple", "django", "django_filters", "django_select2", "drf_spectacular", "imagehash", "pytest", "pytest_django", "rest_framework", "sorl", "storages"]

[tool.ruff]
fix = true
line-length = 95
show-fixes = true
target-version = "py310"
lint.ignore = ["A003", "RUF012", "SLF001", "ISC001"]
select = [
    "A",
    "B",
    "BLE",
    "C40",
    "DJ",
    "E",
    "F",
    "G",
    "I",
    "ICN",
    "INP",
    "ISC",
    "N",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "TID",
    "UP",
    "W",
    "YTT",
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.lint.per-file-ignores]
"users/migrations/*.py" = ["E501", "N806"]
"comicsdb/migrations/*.py" = ["E501", "N806"]
"comicsdb/tests/*.py" = ["PLR2004", "PT004", "S101"]
"metron/tests.py" = ["S101"]
"users/tests/*.py" = ["S101"]

[tool.coverage.run]
source = ["comicsdb", "users", "metron"]

[tool.coverage.report]
show_missing = true
