# Generated by Django 5.2.8 on 2025-11-18 18:35

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comicsdb", "0046_remove_flatpages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("desc", models.TextField(blank=True, verbose_name="Description")),
                (
                    "cv_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Comic Vine ID"
                    ),
                ),
                (
                    "gcd_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="GCD ID"
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "created_on",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this list is private (only visible to the owner)",
                    ),
                ),
                (
                    "attribution_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CBRO", "Comic Book Reading Orders"),
                            ("CMRO", "Complete Marvel Reading Orders"),
                            ("CBH", "Comic Book Herald"),
                            ("CBT", "Comic Book Treasury"),
                            ("MG", "Marvel Guides"),
                            ("HTLC", "How To Love Comics"),
                            ("LOCG", "League of ComicGeeks"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Source where this reading list information was obtained",
                        max_length=10,
                    ),
                ),
                (
                    "attribution_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the specific page where this reading list was obtained",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this reading list",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "attribution_source", "user"],
            },
        ),
        migrations.CreateModel(
            name="ReadingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Position of this issue in the reading list"
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_list_items",
                        to="comicsdb.issue",
                    ),
                ),
                (
                    "reading_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_list_items",
                        to="reading_lists.readinglist",
                    ),
                ),
            ],
            options={
                "ordering": ["reading_list", "order"],
            },
        ),
        migrations.AddField(
            model_name="readinglist",
            name="issues",
            field=models.ManyToManyField(
                blank=True,
                related_name="in_reading_lists",
                through="reading_lists.ReadingListItem",
                to="comicsdb.issue",
            ),
        ),
        migrations.AddIndex(
            model_name="readinglistitem",
            index=models.Index(fields=["reading_list", "order"], name="reading_list_order_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="readinglistitem",
            unique_together={("reading_list", "issue")},
        ),
        migrations.AlterUniqueTogether(
            name="readinglist",
            unique_together={("user", "name")},
        ),
    ]
