# Generated by Django 5.2.8 on 2025-11-16 12:53

import django.db.models.deletion
import django.db.models.functions.datetime
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comicsdb", "0046_remove_flatpages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalReadingList",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("desc", models.TextField(blank=True, verbose_name="Description")),
                (
                    "cv_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Comic Vine ID"
                    ),
                ),
                (
                    "gcd_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="GCD ID"
                    ),
                ),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "created_on",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this list is private (only visible to the owner)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The user who owns this reading list",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical reading list",
                "verbose_name_plural": "historical reading lists",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReadingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("desc", models.TextField(blank=True, verbose_name="Description")),
                (
                    "cv_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Comic Vine ID"
                    ),
                ),
                (
                    "gcd_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="GCD ID"
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "created_on",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this list is private (only visible to the owner)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this reading list",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReadingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Position of this issue in the reading list"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_list_items",
                        to="comicsdb.issue",
                    ),
                ),
                (
                    "reading_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_list_items",
                        to="reading_lists.readinglist",
                    ),
                ),
            ],
            options={
                "ordering": ["reading_list", "order", "created_on"],
            },
        ),
        migrations.AddField(
            model_name="readinglist",
            name="issues",
            field=models.ManyToManyField(
                blank=True,
                related_name="in_reading_lists",
                through="reading_lists.ReadingListItem",
                to="comicsdb.issue",
            ),
        ),
        migrations.AddIndex(
            model_name="readinglistitem",
            index=models.Index(fields=["reading_list", "order"], name="reading_list_order_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="readinglistitem",
            unique_together={("reading_list", "issue")},
        ),
        migrations.AlterUniqueTogether(
            name="readinglist",
            unique_together={("user", "name")},
        ),
    ]
