# Generated by Django 5.2.9 on 2025-12-08 17:09

from django.db import migrations


def create_reading_list_editor_group(apps, schema_editor):
    """Create the 'reading list editor' group for managing Metron's reading lists."""
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="reading list editor")


def delete_reading_list_editor_group(apps, schema_editor):
    """Remove the 'reading list editor' group (reverse operation)."""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="reading list editor").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("reading_lists", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_reading_list_editor_group,
            reverse_code=delete_reading_list_editor_group,
        ),
    ]
