# Generated by Django 5.2.8 on 2025-11-18 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reading_lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="readinglist",
            options={"ordering": ["name", "attribution_source", "user"]},
        ),
    ]
