# Generated by Django 5.2.9 on 2025-12-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading_lists", "0003_readinglistrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglistitem",
            name="issue_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PROLOGUE", "Prologue"),
                    ("CORE", "Core Issue"),
                    ("TIE_IN", "Tie-In"),
                    ("EPILOGUE", "Epilogue"),
                ],
                help_text="Optional categorization of this issue's role in the reading list",
                max_length=10,
            ),
        ),
    ]
