# Generated by Django 5.2.12 on 2026-03-22 18:07

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reading_lists", "0004_readinglistitem_issue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglist",
            name="image",
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to="reading_list/%Y/%m/%d/"),
        ),
    ]
