# Generated by Django 5.2.12 on 2026-03-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading_lists", "0005_add_image_to_readinglist"),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglist",
            name="list_type",
            field=models.CharField(
                choices=[
                    ("EVENT", "Event"),
                    ("STORY", "Story"),
                    ("CHARACTERS", "Characters"),
                    ("TEAMS", "Teams"),
                    ("MASTER", "Master"),
                ],
                default="EVENT",
                help_text="The type of reading list",
                max_length=10,
            ),
        ),
    ]
