# Generated by Django 5.2.12 on 2026-03-29 14:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reading_lists", "0006_readinglist_list_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="readinglist",
            unique_together={("user", "name", "attribution_source")},
        ),
    ]
