# Generated by Django 6.0.6 on 2026-06-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading_lists", "0007_alter_readinglist_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readinglistitem",
            name="order",
            field=models.PositiveIntegerField(
                default=1, help_text="Position of this issue in the reading list"
            ),
        ),
    ]
