# Generated by Django 6.0.6 on 2026-06-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading_lists", "0009_renumber_order_from_zero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readinglist",
            name="list_type",
            field=models.CharField(
                choices=[
                    ("CREATOR", "Creator"),
                    ("EVENT", "Event"),
                    ("STORY", "Story"),
                    ("CHARACTERS", "Characters"),
                    ("TEAMS", "Teams"),
                    ("MASTER", "Master"),
                ],
                default="EVENT",
                help_text="The type of reading list",
                max_length=10,
            ),
        ),
    ]
