# Generated by Django 6.0.7 on 2026-07-20 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading_lists", "0010_add_creator_list_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglist",
            name="next",
            field=models.ForeignKey(
                blank=True,
                help_text="The reading list that comes after this one in a reading order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="reading_lists.readinglist",
            ),
        ),
        migrations.AddField(
            model_name="readinglist",
            name="previous",
            field=models.ForeignKey(
                blank=True,
                help_text="The reading list that comes before this one in a reading order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="reading_lists.readinglist",
            ),
        ),
    ]
