# Generated by Django 6.0.7 on 2026-07-21 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reading_lists", "0011_alter_readinglistrating_rating"),
        ("reading_lists", "0011_readinglist_next_readinglist_previous"),
    ]

    operations = []
