# Generated by Django 5.1.4 on 2024-12-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0033_alter_series_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="arc",
            name="gcd_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="GCD ID"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="gcd_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="GCD ID"
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="gcd_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="GCD ID"
            ),
        ),
        migrations.AddField(
            model_name="imprint",
            name="gcd_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="GCD ID"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="gcd_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="GCD ID"
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="gcd_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="GCD ID"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="gcd_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="GCD ID"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="gcd_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="GCD ID"
            ),
        ),
        migrations.AddField(
            model_name="universe",
            name="gcd_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="GCD ID"
            ),
        ),
        migrations.AlterField(
            model_name="arc",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Comic Vine ID"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Comic Vine ID"
            ),
        ),
        migrations.AlterField(
            model_name="creator",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Comic Vine ID"
            ),
        ),
        migrations.AlterField(
            model_name="imprint",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Comic Vine ID"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Comic Vine ID"
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Comic Vine ID"
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Comic Vine ID"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Comic Vine ID"
            ),
        ),
        migrations.AlterField(
            model_name="universe",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Comic Vine ID"
            ),
        ),
    ]
