# Generated by Django 5.1.5 on 2025-01-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0034_gcd_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="alt_number",
            field=models.CharField(blank=True, max_length=25, verbose_name="Alternative Number"),
        ),
    ]
