# Generated by Django 5.1.5 on 2025-01-20 16:29

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0035_issue_alt_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="country",
            field=django_countries.fields.CountryField(default="US", max_length=2),
        ),
    ]
