# Generated by Django 5.1.9 on 2025-06-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0037_alter_arrayfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="foc_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Final Order Cutoff Date"
            ),
        ),
    ]
