# Generated by Django 5.1.4 on 2025-07-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0038_issue_foc_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="sku",
            field=models.CharField(blank=True, max_length=12, verbose_name="Distributor SKU"),
        ),
    ]
