# Generated by Django 5.2.5 on 2025-09-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0039_alter_issue_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="sku",
            field=models.CharField(blank=True, max_length=12, verbose_name="Distributor SKU"),
        ),
    ]
