# Generated by Django 5.2.7 on 2025-10-25 13:48

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0042_migrate_price_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="new_price",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="new_price_currency",
        ),
        migrations.AddField(
            model_name="issue",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Cover Price"
            ),
        ),
    ]
