# Generated by Django 5.2.7 on 2025-11-03 19:24

from django.db import migrations


def remove_flatpages_tables(apps, schema_editor):
    """Remove flatpages tables since we've removed the app."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS django_flatpage_sites CASCADE;")
        cursor.execute("DROP TABLE IF EXISTS django_flatpage CASCADE;")


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0045_add_simple_history"),
    ]

    operations = [
        migrations.RunPython(
            remove_flatpages_tables,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
