# Generated by Django 5.2.11 on 2026-02-24 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0046_remove_flatpages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['cover_hash'], name='issue_cover_hash_idx'),
        ),
    ]
