# Generated by Django 5.2.11 on 2026-02-25 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0047_add_additional_issue_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['cv_id'], name='series_cv_id_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['gcd_id'], name='series_gcd_id_idx'),
        ),
    ]
