# Generated by Django 5.2.11 on 2026-02-25 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0048_add_series_cv_id_gcd_id_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="arc",
            index=models.Index(fields=["cv_id"], name="arc_cv_id_idx"),
        ),
        migrations.AddIndex(
            model_name="arc",
            index=models.Index(fields=["gcd_id"], name="arc_gcd_id_idx"),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(fields=["cv_id"], name="character_cv_id_idx"),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(fields=["gcd_id"], name="character_gcd_id_idx"),
        ),
        migrations.AddIndex(
            model_name="creator",
            index=models.Index(fields=["cv_id"], name="creator_cv_id_idx"),
        ),
        migrations.AddIndex(
            model_name="creator",
            index=models.Index(fields=["gcd_id"], name="creator_gcd_id_idx"),
        ),
        migrations.AddIndex(
            model_name="imprint",
            index=models.Index(fields=["cv_id"], name="imprint_cv_id_idx"),
        ),
        migrations.AddIndex(
            model_name="imprint",
            index=models.Index(fields=["gcd_id"], name="imprint_gcd_id_idx"),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(fields=["cv_id"], name="publisher_cv_id_idx"),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(fields=["gcd_id"], name="publisher_gcd_id_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["cv_id"], name="team_cv_id_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["gcd_id"], name="team_gcd_id_idx"),
        ),
        migrations.AddIndex(
            model_name="universe",
            index=models.Index(fields=["cv_id"], name="universe_cv_id_idx"),
        ),
        migrations.AddIndex(
            model_name="universe",
            index=models.Index(fields=["gcd_id"], name="universe_gcd_id_idx"),
        ),
    ]
