# Generated by Django 5.2.13 on 2026-04-15 20:01

import django.contrib.postgres.indexes
import django.contrib.postgres.lookups
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0049_add_cv_gcd_id_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER FUNCTION unaccent(text) IMMUTABLE;",
            reverse_sql="ALTER FUNCTION unaccent(text) STABLE;",
        ),
        migrations.RemoveIndex(
            model_name="series",
            name="series_name_idx",
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                models.F("series"),
                django.db.models.functions.text.Upper("number"),
                name="issue_series_upper_num_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="series",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        django.contrib.postgres.lookups.Unaccent("name")
                    ),
                    name="gin_trgm_ops",
                ),
                name="series_name_unaccent_trgm_idx",
            ),
        ),
    ]
