# Generated by Django 5.2.12 on 2026-04-25 17:42

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0051_replace_name_btree_with_unaccent_trgm_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalissue",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("GBP", "British Pound"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("GBP", "British Pound"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="variant",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("GBP", "British Pound"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
