# Generated by Django 6.0.7 on 2026-07-24 15:04

import django.contrib.postgres.indexes
import django.contrib.postgres.lookups
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0052_alter_historicalissue_price_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="arc",
            name="arc_name_unaccent_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="character",
            name="character_name_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="creator",
            name="creator_name_unaccent_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="imprint",
            name="imprint_name_unaccent_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="publisher",
            name="publisher_name_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="series",
            name="series_name_unaccent_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="team",
            name="team_name_unaccent_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="universe",
            name="universe_name_trgm_idx",
        ),
        migrations.AddIndex(
            model_name="arc",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        django.contrib.postgres.lookups.Unaccent("name")
                    ),
                    name="gin_trgm_ops",
                ),
                name="arc_name_unaccent_trgm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        django.contrib.postgres.lookups.Unaccent("name")
                    ),
                    name="gin_trgm_ops",
                ),
                name="character_name_trgm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="creator",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        django.contrib.postgres.lookups.Unaccent("name")
                    ),
                    name="gin_trgm_ops",
                ),
                name="creator_name_unaccent_trgm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="imprint",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        django.contrib.postgres.lookups.Unaccent("name")
                    ),
                    name="gin_trgm_ops",
                ),
                name="imprint_name_unaccent_trgm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        django.contrib.postgres.lookups.Unaccent("name")
                    ),
                    name="gin_trgm_ops",
                ),
                name="publisher_name_trgm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="series",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        django.contrib.postgres.lookups.Unaccent("name")
                    ),
                    name="gin_trgm_ops",
                ),
                name="series_name_unaccent_trgm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        django.contrib.postgres.lookups.Unaccent("name")
                    ),
                    name="gin_trgm_ops",
                ),
                name="team_name_unaccent_trgm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="universe",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        django.contrib.postgres.lookups.Unaccent("name")
                    ),
                    name="gin_trgm_ops",
                ),
                name="universe_name_trgm_idx",
            ),
        ),
    ]
