# Generated by Django 6.0.7 on 2026-07-24 13:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0053_fix_unaccent_trgm_index_case_folding"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalseries",
            name="alt_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                verbose_name="Alternative Names",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="alt_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                verbose_name="Alternative Names",
            ),
        ),
    ]
