# Generated by Django 6.0.7 on 2026-07-24 16:29

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations

import comicsdb.db_functions


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0054_series_alt_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION public.array_to_string_immutable(anyarray, text)
                RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE AS
                $$ SELECT array_to_string($1, $2) $$;
            """,
            reverse_sql="""
                DROP FUNCTION IF EXISTS public.array_to_string_immutable(anyarray, text);
            """,
        ),
        migrations.AddIndex(
            model_name="series",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        comicsdb.db_functions.ArrayToString("alt_names")
                    ),
                    name="gin_trgm_ops",
                ),
                name="series_alt_names_trgm_idx",
            ),
        ),
    ]
