# Generated by Django 6.1.1 on 2026-10-05 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0056_historicalpublisher_alt_names_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variant",
            options={"ordering": ["issue", "name"]},
        ),
        migrations.RemoveIndex(
            model_name="variant",
            name="issue_idx",
        ),
    ]
