# Generated by Django 6.1.1 on 2026-10-06 12:43

from django.db import migrations, models

import comicsdb.validators


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0057_alter_variant_options_remove_issue_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalissue",
            name="upc",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[comicsdb.validators.validate_upc],
                verbose_name="UPC Code",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="upc",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[comicsdb.validators.validate_upc],
                verbose_name="UPC Code",
            ),
        ),
        migrations.AlterField(
            model_name="variant",
            name="upc",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[comicsdb.validators.validate_upc],
                verbose_name="UPC Code",
            ),
        ),
    ]
