# Generated by Django 5.2.9 on 2025-12-09 14:41

import django.db.models.deletion
import django.db.models.functions.datetime
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comicsdb", "0046_remove_flatpages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(default=1, help_text="Number of copies owned"),
                ),
                (
                    "book_format",
                    models.CharField(
                        choices=[("PRINT", "Print"), ("DIGITAL", "Digital"), ("BOTH", "Both")],
                        default="PRINT",
                        help_text="Format of the comic (print, digital, or both)",
                        max_length=10,
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, help_text="Date when the issue was purchased", null=True
                    ),
                ),
                (
                    "purchase_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "purchase_price",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price paid for this issue",
                        max_digits=7,
                        null=True,
                        verbose_name="Purchase Price",
                    ),
                ),
                (
                    "purchase_store",
                    models.CharField(
                        blank=True, help_text="Store or vendor where purchased", max_length=255
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location where the issue is stored",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this collection item"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "issue",
                    models.ForeignKey(
                        help_text="The issue in this collection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_collections",
                        to="comicsdb.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this collection item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Item",
                "verbose_name_plural": "Collection Items",
                "ordering": ["user", "issue__series__sort_name", "issue__cover_date"],
                "indexes": [
                    models.Index(fields=["user", "issue"], name="user_issue_idx"),
                    models.Index(fields=["user", "purchase_date"], name="user_purchase_date_idx"),
                    models.Index(fields=["user", "book_format"], name="user_format_idx"),
                ],
                "unique_together": {("user", "issue")},
            },
        ),
    ]
