# Generated by Django 5.2.9 on 2025-12-13 19:42
# ruff: noqa: E501

from decimal import Decimal

import django.db.models.deletion
import django.db.models.functions.datetime
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comicsdb", "0046_remove_flatpages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(default=1, help_text="Number of copies owned"),
                ),
                (
                    "book_format",
                    models.CharField(
                        choices=[("PRINT", "Print"), ("DIGITAL", "Digital"), ("BOTH", "Both")],
                        default="PRINT",
                        help_text="Format of the comic (print, digital, or both)",
                        max_length=10,
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, help_text="Date when the issue was purchased", null=True
                    ),
                ),
                (
                    "purchase_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "purchase_price",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price paid for this issue",
                        max_digits=7,
                        null=True,
                        verbose_name="Purchase Price",
                    ),
                ),
                (
                    "purchase_store",
                    models.CharField(
                        blank=True, help_text="Store or vendor where purchased", max_length=255
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location where the issue is stored",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this collection item"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "issue",
                    models.ForeignKey(
                        help_text="The issue in this collection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_collections",
                        to="comicsdb.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this collection item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "date_read",
                    models.DateField(
                        blank=True, help_text="Date when the issue was read", null=True
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, help_text="Whether the issue has been read"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Star rating (1-5) for this issue",
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        blank=True,
                        choices=[
                            (Decimal("10.0"), "10.0 (Gem Mint)"),
                            (Decimal("9.9"), "9.9 (Mint)"),
                            (Decimal("9.8"), "9.8 (NM/M - Near Mint/Mint)"),
                            (Decimal("9.6"), "9.6 (NM+ - Near Mint+)"),
                            (Decimal("9.4"), "9.4 (NM - Near Mint)"),
                            (Decimal("9.2"), "9.2 (NM- - Near Mint-)"),
                            (Decimal("9.0"), "9.0 (VF/NM - Very Fine/Near Mint)"),
                            (Decimal("8.5"), "8.5 (VF+ - Very Fine+)"),
                            (Decimal("8.0"), "8.0 (VF - Very Fine)"),
                            (Decimal("7.5"), "7.5 (VF- - Very Fine-)"),
                            (Decimal("7.0"), "7.0 (FN/VF - Fine/Very Fine)"),
                            (Decimal("6.5"), "6.5 (FN+ - Fine+)"),
                            (Decimal("6.0"), "6.0 (FN - Fine)"),
                            (Decimal("5.5"), "5.5 (FN- - Fine-)"),
                            (Decimal("5.0"), "5.0 (VG/FN - Very Good/Fine)"),
                            (Decimal("4.5"), "4.5 (VG+ - Very Good+)"),
                            (Decimal("4.0"), "4.0 (VG - Very Good)"),
                            (Decimal("3.5"), "3.5 (VG- - Very Good-)"),
                            (Decimal("3.0"), "3.0 (GD/VG - Good/Very Good)"),
                            (Decimal("2.5"), "2.5 (GD+ - Good+)"),
                            (Decimal("2.0"), "2.0 (GD - Good)"),
                            (Decimal("1.8"), "1.8 (GD- - Good-)"),
                            (Decimal("1.5"), "1.5 (FR/GD - Fair/Good)"),
                            (Decimal("1.0"), "1.0 (FR - Fair)"),
                            (Decimal("0.5"), "0.5 (PR - Poor)"),
                        ],
                        decimal_places=1,
                        help_text="Comic book grade (CGC scale)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "grading_company",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CGC", "CGC (Certified Guaranty Company)"),
                            ("CBCS", "CBCS (Comic Book Certification Service)"),
                            ("PGX", "PGX (Professional Grading Experts)"),
                        ],
                        default="",
                        help_text="Professional grading company (leave blank for user-assessed grade)",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Item",
                "verbose_name_plural": "Collection Items",
                "ordering": ["user", "issue__series__sort_name", "issue__cover_date"],
                "indexes": [
                    models.Index(fields=["user", "issue"], name="user_issue_idx"),
                    models.Index(fields=["user", "purchase_date"], name="user_purchase_date_idx"),
                    models.Index(fields=["user", "book_format"], name="user_format_idx"),
                    models.Index(fields=["user", "is_read"], name="user_is_read_idx"),
                    models.Index(fields=["user", "grade"], name="user_grade_idx"),
                    models.Index(
                        fields=["user", "grading_company"], name="user_grading_company_idx"
                    ),
                ],
                "unique_together": {("user", "issue")},
            },
        ),
    ]
