# Generated by Django 5.2.9 on 2025-12-11 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0046_remove_flatpages"),
        ("user_collection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="date_read",
            field=models.DateField(blank=True, help_text="Date when the issue was read", null=True),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="is_read",
            field=models.BooleanField(default=False, help_text="Whether the issue has been read"),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(fields=["user", "is_read"], name="user_is_read_idx"),
        ),
    ]
