# Generated by Django 5.2.8 on 2026-01-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="date_read",
            field=models.DateTimeField(
                blank=True, help_text="Date and time when the issue was read", null=True
            ),
        ),
    ]
