# Generated by Django 5.2.9 on 2026-01-10 14:49

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


def migrate_existing_read_dates(apps, schema_editor):
    """Migrate existing date_read values to ReadDate entries."""
    CollectionItem = apps.get_model("user_collection", "CollectionItem")
    ReadDate = apps.get_model("user_collection", "ReadDate")

    items_with_dates = CollectionItem.objects.filter(date_read__isnull=False)
    read_dates = [
        ReadDate(collection_item=item, read_date=item.date_read) for item in items_with_dates
    ]
    ReadDate.objects.bulk_create(read_dates)


def reverse_migrate_read_dates(apps, schema_editor):
    """Reverse migration: keep date_read field as-is when rolling back."""
    # No action needed - date_read field is preserved


class Migration(migrations.Migration):

    dependencies = [
        ("user_collection", "0002_collectionitem_date_read_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="date_read",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the issue was last read (synced from read_dates)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ReadDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "read_date",
                    models.DateTimeField(help_text="Date and time when the issue was read"),
                ),
                (
                    "created_on",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "collection_item",
                    models.ForeignKey(
                        help_text="The collection item this read date belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_dates",
                        to="user_collection.collectionitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Read Date",
                "verbose_name_plural": "Read Dates",
                "ordering": ["-read_date"],
                "indexes": [
                    models.Index(
                        fields=["collection_item", "-read_date"], name="collection_read_date_idx"
                    )
                ],
            },
        ),
        migrations.RunPython(migrate_existing_read_dates, reverse_migrate_read_dates),
    ]
