# Generated by Django 5.2.9 on 2025-12-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_collection", "0003_add_rating_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Star rating (0.5-5.0 in 0.5 increments) for this issue",
                max_digits=2,
                null=True,
            ),
        ),
    ]
