# Generated by Django 5.2.12 on 2026-04-25 17:42

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_collection", "0003_add_readdate_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="purchase_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("GBP", "British Pound"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
