# Generated by Django 5.2.9 on 2025-12-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_collection", "0004_change_rating_to_decimal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                help_text="Star rating (1-5) for this issue",
                null=True,
            ),
        ),
    ]
