# Generated by Django 5.2.9 on 2025-12-13 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0046_remove_flatpages"),
        ("user_collection", "0005_revert_rating_to_integer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="grade",
            field=models.DecimalField(
                blank=True,
                choices=[
                    (10.0, "10.0 (Gem Mint)"),
                    (9.9, "9.9 (Mint)"),
                    (9.8, "9.8 (NM/M - Near Mint/Mint)"),
                    (9.6, "9.6 (NM+ - Near Mint+)"),
                    (9.4, "9.4 (NM - Near Mint)"),
                    (9.2, "9.2 (NM- - Near Mint-)"),
                    (9.0, "9.0 (VF/NM - Very Fine/Near Mint)"),
                    (8.5, "8.5 (VF+ - Very Fine+)"),
                    (8.0, "8.0 (VF - Very Fine)"),
                    (7.5, "7.5 (VF- - Very Fine-)"),
                    (7.0, "7.0 (FN/VF - Fine/Very Fine)"),
                    (6.5, "6.5 (FN+ - Fine+)"),
                    (6.0, "6.0 (FN - Fine)"),
                    (5.5, "5.5 (FN- - Fine-)"),
                    (5.0, "5.0 (VG/FN - Very Good/Fine)"),
                    (4.5, "4.5 (VG+ - Very Good+)"),
                    (4.0, "4.0 (VG - Very Good)"),
                    (3.5, "3.5 (VG- - Very Good-)"),
                    (3.0, "3.0 (GD/VG - Good/Very Good)"),
                    (2.5, "2.5 (GD+ - Good+)"),
                    (2.0, "2.0 (GD - Good)"),
                    (1.8, "1.8 (GD- - Good-)"),
                    (1.5, "1.5 (FR/GD - Fair/Good)"),
                    (1.0, "1.0 (FR - Fair)"),
                    (0.5, "0.5 (PR - Poor)"),
                ],
                decimal_places=1,
                help_text="Comic book grade (CGC scale)",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="grading_company",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CGC", "CGC (Certified Guaranty Company)"),
                    ("CBCS", "CBCS (Comic Book Certification Service)"),
                    ("PGX", "PGX (Professional Grading Experts)"),
                ],
                help_text="Professional grading company (leave blank for user-assessed grade)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(fields=["user", "grade"], name="user_grade_idx"),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(fields=["user", "grading_company"], name="user_grading_company_idx"),
        ),
    ]
