# Generated by Django 5.2.9 on 2025-12-13 19:31

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_collection", "0006_collectionitem_grade_collectionitem_grading_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="grade",
            field=models.DecimalField(
                blank=True,
                choices=[
                    (Decimal("10.0"), "10.0 (Gem Mint)"),
                    (Decimal("9.9"), "9.9 (Mint)"),
                    (Decimal("9.8"), "9.8 (NM/M - Near Mint/Mint)"),
                    (Decimal("9.6"), "9.6 (NM+ - Near Mint+)"),
                    (Decimal("9.4"), "9.4 (NM - Near Mint)"),
                    (Decimal("9.2"), "9.2 (NM- - Near Mint-)"),
                    (Decimal("9.0"), "9.0 (VF/NM - Very Fine/Near Mint)"),
                    (Decimal("8.5"), "8.5 (VF+ - Very Fine+)"),
                    (Decimal("8.0"), "8.0 (VF - Very Fine)"),
                    (Decimal("7.5"), "7.5 (VF- - Very Fine-)"),
                    (Decimal("7.0"), "7.0 (FN/VF - Fine/Very Fine)"),
                    (Decimal("6.5"), "6.5 (FN+ - Fine+)"),
                    (Decimal("6.0"), "6.0 (FN - Fine)"),
                    (Decimal("5.5"), "5.5 (FN- - Fine-)"),
                    (Decimal("5.0"), "5.0 (VG/FN - Very Good/Fine)"),
                    (Decimal("4.5"), "4.5 (VG+ - Very Good+)"),
                    (Decimal("4.0"), "4.0 (VG - Very Good)"),
                    (Decimal("3.5"), "3.5 (VG- - Very Good-)"),
                    (Decimal("3.0"), "3.0 (GD/VG - Good/Very Good)"),
                    (Decimal("2.5"), "2.5 (GD+ - Good+)"),
                    (Decimal("2.0"), "2.0 (GD - Good)"),
                    (Decimal("1.8"), "1.8 (GD- - Good-)"),
                    (Decimal("1.5"), "1.5 (FR/GD - Fair/Good)"),
                    (Decimal("1.0"), "1.0 (FR - Fair)"),
                    (Decimal("0.5"), "0.5 (PR - Poor)"),
                ],
                decimal_places=1,
                help_text="Comic book grade (CGC scale)",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="grading_company",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CGC", "CGC (Certified Guaranty Company)"),
                    ("CBCS", "CBCS (Comic Book Certification Service)"),
                    ("PGX", "PGX (Professional Grading Experts)"),
                ],
                default="",
                help_text="Professional grading company (leave blank for user-assessed grade)",
                max_length=10,
            ),
        ),
    ]
