# Generated by Django 5.2.14 on 2026-05-17 15:51

from decimal import Decimal

import django.db.models.deletion
import django.db.models.functions.datetime
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comicsdb", "0052_alter_historicalissue_price_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "created_on",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wish_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wish List",
                "verbose_name_plural": "Wish Lists",
            },
        ),
        migrations.CreateModel(
            name="WishListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WANTED", "Wanted"),
                            ("FOUND", "Found"),
                            ("ACQUIRED", "Acquired"),
                        ],
                        default="WANTED",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=3
                    ),
                ),
                (
                    "desired_grade",
                    models.DecimalField(
                        blank=True,
                        choices=[
                            (Decimal("10.0"), "10.0 (Gem Mint)"),
                            (Decimal("9.9"), "9.9 (Mint)"),
                            (Decimal("9.8"), "9.8 (NM/M - Near Mint/Mint)"),
                            (Decimal("9.6"), "9.6 (NM+ - Near Mint+)"),
                            (Decimal("9.4"), "9.4 (NM - Near Mint)"),
                            (Decimal("9.2"), "9.2 (NM- - Near Mint-)"),
                            (Decimal("9.0"), "9.0 (VF/NM - Very Fine/Near Mint)"),
                            (Decimal("8.5"), "8.5 (VF+ - Very Fine+)"),
                            (Decimal("8.0"), "8.0 (VF - Very Fine)"),
                            (Decimal("7.5"), "7.5 (VF- - Very Fine-)"),
                            (Decimal("7.0"), "7.0 (FN/VF - Fine/Very Fine)"),
                            (Decimal("6.5"), "6.5 (FN+ - Fine+)"),
                            (Decimal("6.0"), "6.0 (FN - Fine)"),
                            (Decimal("5.5"), "5.5 (FN- - Fine-)"),
                            (Decimal("5.0"), "5.0 (VG/FN - Very Good/Fine)"),
                            (Decimal("4.5"), "4.5 (VG+ - Very Good+)"),
                            (Decimal("4.0"), "4.0 (VG - Very Good)"),
                            (Decimal("3.5"), "3.5 (VG- - Very Good-)"),
                            (Decimal("3.0"), "3.0 (GD/VG - Good/Very Good)"),
                            (Decimal("2.5"), "2.5 (GD+ - Good+)"),
                            (Decimal("2.0"), "2.0 (GD - Good)"),
                            (Decimal("1.8"), "1.8 (GD- - Good-)"),
                            (Decimal("1.5"), "1.5 (FR/GD - Fair/Good)"),
                            (Decimal("1.0"), "1.0 (FR - Fair)"),
                            (Decimal("0.5"), "0.5 (PR - Poor)"),
                        ],
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "max_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("GBP", "British Pound"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "max_price",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Maximum Price",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "added_on",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wish_list_items",
                        to="comicsdb.issue",
                    ),
                ),
                (
                    "wish_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wish_list_items",
                        to="wish_list.wishlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wish List Item",
                "verbose_name_plural": "Wish List Items",
                "ordering": ["priority", "issue__series__sort_name", "issue__cover_date"],
                "indexes": [
                    models.Index(fields=["wish_list", "status"], name="wish_list_status_idx"),
                    models.Index(fields=["wish_list", "priority"], name="wish_list_priority_idx"),
                ],
                "unique_together": {("wish_list", "issue")},
            },
        ),
    ]
