# Generated by Django 5.2.14 on 2026-05-17 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wish_list", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="is_private",
        ),
    ]
