# Generated by Django 5.2.14 on 2026-05-21 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wish_list", "0002_remove_wishlist_is_private"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlist",
            options={
                "ordering": ["user"],
                "verbose_name": "Wish List",
                "verbose_name_plural": "Wish Lists",
            },
        ),
    ]
