# Generated by Django 6.0.7 on 2026-08-15 16:14

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wish_list", "0003_alter_wishlist_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlistitem",
            name="max_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("ITL", "Italian Lira"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
