services:
  test:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    container_name: metron_test
    command: pytest -v
    volumes:
      - ..:/app
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: myprojectuser
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  web_static:
  web_media:
