# Generated by Django 5.2.14 on 2026-05-17 15:51

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comicsdb", "0052_alter_historicalissue_price_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PullList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "created_on",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pull List",
                "verbose_name_plural": "Pull Lists",
            },
        ),
        migrations.CreateModel(
            name="PullListSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "added_on",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "pull_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_list_series",
                        to="pull_list.pulllist",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_list_series",
                        to="comicsdb.series",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pull List Series",
                "verbose_name_plural": "Pull List Series",
                "ordering": ["series__sort_name"],
            },
        ),
        migrations.AddField(
            model_name="pulllist",
            name="series",
            field=models.ManyToManyField(
                blank=True,
                related_name="in_pull_lists",
                through="pull_list.PullListSeries",
                to="comicsdb.series",
            ),
        ),
        migrations.AddIndex(
            model_name="pulllistseries",
            index=models.Index(fields=["pull_list", "series"], name="pull_list_series_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="pulllistseries",
            unique_together={("pull_list", "series")},
        ),
    ]
