# Generated by Django 5.2.14 on 2026-05-21 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pull_list", "0002_remove_pulllist_is_private"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pulllist",
            options={
                "ordering": ["user"],
                "verbose_name": "Pull List",
                "verbose_name_plural": "Pull Lists",
            },
        ),
    ]
