# Generated by Django 6.0.7 on 2026-07-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue_ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuerating",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                help_text="Star rating (1-5)",
            ),
        ),
    ]
